version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: npm install
      - run: npm test

  deploy:
    machine: true
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - deploy:
          name: Deploy to server
          command: rsync -va --delete ./build/ ${WEBSERVER}:${WEBADDRESS}

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master