export const actionTypes = {
  CLEAR_ALL: "CLEAR_ALL",
  REQUEST_STOPS: "REQUEST_STOPS",
  RECEIVE_STOPS: "RECEIVE_STOPS",
  REQUEST_LINES: "REQUEST_LINES",
  RECEIVE_LINES: "RECEIVE_LINES",
  RECEIVE_DIRS: "RECEIVE_DIRS",
  REQUEST_ARRIVALS: "REQUEST_ARRIVALS",
  RECEIVE_ARRIVALS: "RECEIVE_ARRIVALS"
}